[book]
authors = ["Arthur Paulino, Damiano Testa, Edward Ayers, Evgenia Karunus, Henrik Böving, Jannis Limperg, Siddhartha Gadgil, Siddharth Bhat"]
language = "zh-CN"
multilingual = false
src = "md"
title = "Lean 4 元编程"

[output.html]
git-repository-url = "https://github.com/Lean-zh/mp-lean-zh"