name: Book

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain $(cat lean-toolchain)
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: build markdown files by mdgen
      run: lake run build
